### ISSUE TITLE
Convert website to golang template

### ISSUE THREAD

**Issue by andey-robins** [andey-robins/gosniffer#3]
Using the golang http templating, change the `index.html` site in the `/website` package to pull data from a web socket and put it into the website for display.

**Comment by dr-brutalov** [comment]
Test

**Comment by andey-robins** [comment]
Template conversion finished in commit `3d7fbae8ecdd9cc3b20c9ca6fb027e0bb5d9443c`

Finalization of the table display will need to wait and be styled after we finalize what data will be presented and how we want to present it. Closing issue for now
